name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install project (dev extras)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Formatting & Lint (black + ruff)
        run: |
          black --check .
          ruff check .

      - name: Type checks (mypy)
        run: |
          mypy src

      - name: Unit tests w/ coverage
        run: |
          pytest --cov=src --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          # token not required for public repos
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  # Optional: stricter static analysis (can be required later)
  pylint:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pylint src || true   # remove `|| true` once you tune rules
